### ISSUE TITLE
Issue with downloading some cover arts from Bandcamp

### ISSUE THREAD

**Issue by kopytko95** [jgchk/better-rym#83] opened 2021-06-09 18:55 UTC
https://thenightisstillyoung.bandcamp.com/album/king-of-the-bees
https://thenightisstillyoung.bandcamp.com/track/true-love-will-find-you-in-the-end

These two for example, i suspect it has something to do with size, as all the images that worked were below ~ 6mb, while a couple that didn't were somewhat bigger

**Comment by jgchk** [comment] 2021-06-28 15:41
these are downloading correctly for me now on the latest release (4.4.0) which I've just put up for review on the chrome store. closing this ticket for now.

if the issue is still happening for you once you get the update, feel free to reopen

**Closed by jgchk** 2021-06-28 15:41 UTC
