### ISSUE TITLE
The extension stops downloading Apple Music albums cover art

### ISSUE THREAD

**Issue by kunehenry** [jgchk/better-rym#185] opened 2023-06-22 00:51 UTC
I'm using Edge browser on MacOS

**Comment by FlorianWolters** [comment] 2023-06-27 18:34
I can confirm this. I'm using Firefox v114.0.2 and the extension v4.25.0.

**Comment by sc113** [comment] 2023-06-27 22:56
The extension has also started to extract incorrectly sized images for music videos. Here https://music.apple.com/gr/music-video/on-on-again/1683514891 the original image is 1912x1072, but BetterRYM got 1200x675.

**Comment by FlorianWolters** [comment] 2023-06-30 12:44
> The extension has also started to extract incorrectly sized images for music videos. Here https://music.apple.com/gr/music-video/on-on-again/1683514891 the original image is 1912x1072, but BetterRYM got 1200x675.

But that is another issue, potentially unrelated to this one. I suggest to create a separate issue for that misbehavior.

In addition: This is a duplicate of #183.

**Comment by FlorianWolters** [comment] 2023-06-30 12:45
Duplicate of #183

**Comment by jgchk** [comment] 2023-07-28 22:38
solved in ca74c1460d9368df4d9a259cc2e9d94bb30f2a67

**Closed by jgchk** 2023-07-28 22:38 UTC

**Comment by jgchk** [comment] 2023-07-28 22:47
incorrect sizing fixed in 24f39abe1b5cf978366268b04c4a2805403a77df

**Comment by kopytko95** [comment] 2023-07-29 11:36
Still doesn't work for me even though it seem like the recent version is already on the chrome webstore (shows yesterday's date for last update), reinstalling didn't help

**Comment by jgchk** [comment] 2023-07-30 17:33
could you send an example link that doesn't work?

**Comment by jgchk** [comment] 2023-07-30 17:46
may have found this issue: c05d8b690e7e99e60fc459be8fd8399a83809f44

check the update as it comes in today and let me know @kopytko95
